/**
 * Pure emitter: named routes → `types/routes.d.ts` module augmentation source.
 *
 * @packageDocumentation
 */

import type { Route } from "./route";

const PARAM_SEGMENT = /:([A-Za-z_][A-Za-z0-9_]*)/g;

function extractPathParams(path: string): string[] {
    const names: string[] = [];

    for (const match of path.matchAll(PARAM_SEGMENT)) {
        const paramName = match[1];
        if (paramName !== undefined && !names.includes(paramName)) {
            names.push(paramName);
        }
    }

    return names;
}

function formatParamsType(paramNames: string[]): string {
    if (paramNames.length === 0) {
        return "Record<never, never>";
    }

    const fields = paramNames.map((name) => `${name}: string`).join("; ");
    return `{ ${fields} }`;
}

/**
 * Emit the contents of a `types/routes.d.ts` artifact from registered routes.
 *
 * Only named routes are included. Output is sorted by name for stable diffs.
 * Duplicate names throw with the conflicting name in the message.
 *
 * @param routes - Routes from `Router.getRoutes()`
 * @returns Full `.d.ts` source (header + `declare module` augmentation)
 * @throws Error when two routes share the same name
 */
export function emitRouteRegistry(routes: Route[]): string {
    const byName = new Map<string, Route>();

    for (const registered of routes) {
        const name = registered.getName();
        if (name === undefined) {
            continue;
        }

        if (byName.has(name)) {
            throw new Error(`Duplicate route name: ${name}`);
        }

        byName.set(name, registered);
    }

    const sortedNames = [...byName.keys()].sort((a, b) => a.localeCompare(b));

    const lines: string[] = [
        "// Generated by `nino routes:compile` — DO NOT EDIT.",
        'declare module "@ninots/routing" {',
        "    interface RouteRegistry {",
    ];

    for (const name of sortedNames) {
        const registered = byName.get(name);
        if (registered === undefined) {
            continue;
        }

        const paramNames = extractPathParams(registered.getPath());
        lines.push(`        ${JSON.stringify(name)}: ${formatParamsType(paramNames)};`);
    }

    lines.push("    }", "}", "");

    return lines.join("\n");
}
