/**
 * Unit tests for emitRouteRegistry and route()/setRouteResolver.
 *
 * @packageDocumentation
 */

import { describe, expect, test } from "bun:test";
import { fileURLToPath } from "node:url";
import { emitRouteRegistry, route, setRouteResolver, Router } from "../../index";
import { createMockHandler } from "../setup";

describe("emitRouteRegistry()", () => {
    test("emits sorted module augmentation with Record<never, never> and params", () => {
        const router = new Router();
        router.get("/users/:id", createMockHandler()).name("users.show");
        router.get("/", createMockHandler()).name("home");
        router.get("/orphan", createMockHandler());

        const dts = emitRouteRegistry(router.getRoutes());

        expect(dts.startsWith("// Generated by `nino routes:compile` — DO NOT EDIT.")).toBe(true);
        expect(dts).toContain('declare module "@ninots/routing"');
        expect(dts).toContain('"home": Record<never, never>;');
        expect(dts).toContain('"users.show": { id: string };');
        expect(dts.indexOf('"home"')).toBeLessThan(dts.indexOf('"users.show"'));
        expect(dts).not.toContain("orphan");
    });

    test("throws on duplicate route names", () => {
        const router = new Router();
        router.get("/a", createMockHandler()).name("dup");
        router.get("/b", createMockHandler()).name("dup");

        expect(() => emitRouteRegistry(router.getRoutes())).toThrow("Duplicate route name: dup");
    });

    test("emits empty registry interface when no named routes", () => {
        const router = new Router();
        router.get("/x", createMockHandler());

        const dts = emitRouteRegistry(router.getRoutes());

        expect(dts).toContain("interface RouteRegistry {");
        expect(dts).not.toMatch(/RouteRegistry \{\s*"[^"]+"/);
    });

    test("includes group prefixes in paths for param extraction", () => {
        const router = new Router();
        router.group({ prefix: "/api" }, () => {
            router.get("/users/:id", createMockHandler()).name("users.show");
        });

        const dts = emitRouteRegistry(router.getRoutes());
        expect(dts).toContain('"users.show": { id: string };');
    });
});

describe("route() / setRouteResolver()", () => {
    test("resolves named routes including group prefixes", () => {
        const router = new Router();
        router.get("/", createMockHandler()).name("home");
        router.group({ prefix: "/api" }, () => {
            router.get("/users/:id", createMockHandler()).name("users.show");
        });
        setRouteResolver(router);

        expect(route("home")).toBe("/");
        expect(route("users.show", { id: "123" })).toBe("/api/users/123");
    });

    test("throws when resolver is not set (isolated process)", async () => {
        const modulePath = fileURLToPath(new URL("../../src/RouteRegistry.ts", import.meta.url));
        const script = `
import { route } from ${JSON.stringify(modulePath)};
try {
  const call = route;
  call("home");
  process.exit(0);
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  if (message.includes("Route resolver not set")) {
    process.exit(2);
  }
  process.exit(1);
}
`;
        const proc = Bun.spawn(["bun", "-e", script], {
            stdout: "pipe",
            stderr: "pipe",
        });
        const exitCode = await proc.exited;
        expect(exitCode).toBe(2);
    });
});
